import { Inter } from "next/font/google";
import "./globals.css";
import LeftMenu from "../components/LeftMenu";
import TopMenu from "../components/TopMenu";
import Logo from "../components/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="page">
          <div className="left-panel">
            <Logo />
            <LeftMenu />
          </div>
          <div className="right-panel">
            <TopMenu />
            <div className="content">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
